apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-clusterip
  labels:
    app: spring-boot-app
spec:
  type: ClusterIP
  selector:
    app: spring-boot-app
  ports:
    - name: http
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on the Pod that the service forwards to
