apiVersion: v1
kind: Service
metadata:
  name: springboot-service-lb
  labels:
    app: springboot-app
spec:
  selector:
    app: spring-boot-app
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80        # Port exposed by the LoadBalancer
        targetPort: 8080  # The port the pods are listening on

