apiVersion: v1
kind: Pod
metadata:
  name: springbootapp-pod02
  labels:
    app: springbootapp
spec:
  nodeName: vm2
  containers:
    - image: harryitpro/springbootapp
      name: springbootapp-container
      ports:
        - containerPort: 8080
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}