apiVersion: v1
kind: Service
metadata:
  name: springbootapp-service-clusterip
  labels:
    app: springbootapp
spec:
  type: ClusterIP
  selector:
    app: springbootapp
  ports:
    - name: http
      port: 80         # Port exposed by the service
      targetPort: 8080 # Port on the Pod that the service forwards to
