apiVersion: v1
kind: Service
metadata:
  name: springbootapp-service-nodeport
  labels:
    app: springbootapp
spec:
  type: NodePort
  selector:
    app: springbootapp
  ports:
    - name: http
      port: 80 # Port exposed inside the cluster
      targetPort: 8080 # Port on the Pod
      nodePort: 30036    # Static port exposed on each node (range: 30000-32767)