apiVersion: v1
kind: Service
metadata:
  name: springboot-service-lb
  labels:
    app: springbootapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the LoadBalancer
      targetPort: 8080  # The port the pods are listening on
  selector:
    app: springbootapp
